/* SPDX-License-Identifier: MIT */
#include "reference_test.h"
#define CB1_TEST_LEGACY_ANALYSIS 1
#include "../src/dvbridge_render.c"

static void witness(struct dvbridge_renderer *r,unsigned which)
{
    /* Independently authored prescribed-tree records. The first preserves the
     * complete original native receipt; the second crosses the L1 rounding bin. */
    const uint32_t records[][12]={
        {0x3eff17de,0x490de0e4,0x3eff17f1,1166400,11,0,1,0,1,0,1,0},
        {0x3eff3041,0x490dee74,0x3eff3042,1166400,11,0,1,0,1,0,1,0},
        {0x3f333334,0x40066668,0x3f333335,3,11,0,1,0,1,0,1,0},
        {0x3ecccccd,0x3fc00000,0x3f19999a,3,11,0,1,0,1,0,1,0}};
    const double rounded[][3]={{.49823,.49823,.49823},{.49842,.49842,.49842},
        {.7,.7,.7},{.4,.5,.6}};
    const uint16_t codes[][3]={{2041,2041,2041},{2042,2042,2042},
        {2867,2867,2867},{1638,2458,2048}};
    /* Frozen descriptor template plus independently authored literal fields
     * and polynomial-division CRC, never generated by the production serializer. */
    const char *packets[]={
        "000000005f00012566000035ea2566f9fceb1c256644ca00000100000008000000080000001c36224301860a5e308e0514000001a63e5affff00000000000000000c00010100000cbd002a02000000060107f907f907f90000000805000000000000000000000000000000000000000000000000000000000000000005c20dfa",
        "000000005f00012566000035ea2566f9fceb1c256644ca00000100000008000000080000001c36224301860a5e308e0514000001a63e5affff00000000000000000c00010100000cbd002a02000000060107fa07fa07fa000000080500000000000000000000000000000000000000000000000000000000000000007ce703cc",
        "000000005f00012566000035ea2566f9fceb1c256644ca00000100000008000000080000001c36224301860a5e308e0514000001a63e5affff00000000000000000c00010100000cbd002a0200000006010b330b330b3300000008050000000000000000000000000000000000000000000000000000000000000000be8d8b7a",
        "000000005f00012566000035ea2566f9fceb1c256644ca00000100000008000000080000001c36224301860a5e308e0514000001a63e5affff00000000000000000c00010100000cbd002a0200000006010666099a0800000000080500000000000000000000000000000000000000000000000000000000000000001187b6e1"};
    const uint32_t *record=records[which];
    size_t bytes;r->dv.source_metadata=task3_fixture(&bytes);assert(r->dv.source_metadata);
    r->dv.active=true;r->dv.groups=record[3];
    r->dv.output.value=(struct dvbridge_dv_policy_snapshot){.identity={11,1,1},
        .nominal_max_nits=1500,.output_generation=DVBRIDGE_ETSI_LEGACY_LITERAL};
    const bool valid=dv_derive(r,record);
    fprintf(stderr,"WITNESS=%u accepted=%d min=%08x sum=%08x max=%08x count=%u\n",
        which,valid,record[0],record[1],record[2],record[3]);
    assert(valid);
    assert(!memcmp(r->dv.output.value.statistics,rounded[which],sizeof(rounded[which])));
    assert(!memcmp(r->dv.output.value.l1,codes[which],sizeof(codes[which])));
    float raw[3];memcpy(raw,record,sizeof(raw));
    const struct dvbridge_dv_policy_snapshot *value=&r->dv.output.value;
    assert(value->raw_statistics[0]==raw[0] && value->raw_statistics[2]==raw[2]);
    assert(value->raw_statistics[1]==(double)raw[1]/record[3]);
    assert(!memcmp(&value->raw_sum,record+1,4) && value->sample_count==record[3]);
    if(which<2)assert(value->raw_statistics[1]<value->raw_statistics[0]);
    if(which==2)assert(value->raw_statistics[1]>value->raw_statistics[2]);
    unsigned packet_count;const uint32_t *packet=dvbridge_packets(r->pending,&packet_count);
    assert(packet_count==1 && strlen(packets[which])==256);
    for(unsigned i=0;i<128;i++){
        unsigned wanted;assert(sscanf(packets[which]+2*i,"%2x",&wanted)==1);
        assert(packet[i]==wanted);
    }
    dvbridge_render_dv_policy_cancel(r);
    assert(dvbridge_render_dv_policy_poll(r)==DVBRIDGE_DV_IDLE);
}
static void corrupt_records(struct dvbridge_renderer *r)
{
    const uint32_t malformed[][2]={{0,0x7fc00000},{1,0x7f800000},{2,0xff800000},
        {0,0xbf000000},{2,0x40000000},{0,0x3f800000},
        {1,0x490de0e3},{1,0x490de0f0},{1,0xbf800000},
        {3,0},{3,1166399},{3,2073601},
        {4,12},{5,1},{6,2},{7,1},{8,2},{9,1},{10,0},{10,2},{11,1}};
    for(unsigned test=0;test<sizeof(malformed)/sizeof(*malformed);test++){
        uint32_t record[12]={0x3eff17de,0x490de0e4,0x3eff17f1,1166400,11,0,1,0,1,0,1,0};
        record[malformed[test][0]]=malformed[test][1];
        size_t bytes;r->dv.source_metadata=task3_fixture(&bytes);assert(r->dv.source_metadata);
        r->dv.active=true;r->dv.groups=1166400;
        r->dv.output.value=(struct dvbridge_dv_policy_snapshot){.identity={11,1,1},
            .nominal_max_nits=1500,.output_generation=DVBRIDGE_ETSI_LEGACY_LITERAL};
        assert(!dv_derive(r,record) && !r->pending && !r->dv.output_metadata);
        fprintf(stderr,"CORRUPT=%u field=%u bits=%08x rejected=1\n",test,malformed[test][0],malformed[test][1]);
        dvbridge_render_dv_policy_cancel(r);assert(dvbridge_render_dv_policy_poll(r)==DVBRIDGE_DV_IDLE);
    }
}
int main(int argc,char **argv)
{
    struct reference_gpu g=reference_gpu_create();
    struct dvbridge_retirement_owner *owner=dvbridge_retirement_owner_create(g.gl->gpu);assert(owner);
    struct dvbridge_renderer *r=dvbridge_renderer_create_with_owner(owner);assert(r);
    if(argc==2)witness(r,(unsigned)strtoul(argv[1],NULL,10));
    else for(unsigned which=0;which<4;which++)witness(r,which);
    corrupt_records(r);
    dvbridge_renderer_destroy(r);assert(dvbridge_retirement_owner_destroy(&owner));reference_gpu_destroy(&g);
}
